// P1P3 — Content (bilingual)
(function () {
  "use strict";
  window.P1P3 = window.P1P3 || {};
  window.P1P3.CONTENT = {
    en: {
      nav: { music: "MUSIC", about: "ABOUT", dossier: "EPK", rider: "RIDER", booking: "BOOKING", live: "LIVE" },
      hero: {
        tagline: "DIVE INTO THE SOUND",
        cta: "ENTER THE CLUB",
        epk: "VIEW EPK",
        scroll: "SCROLL",
        caption: "DJ / PRODUCER — PEAK TIME / MELODIC UNDERGROUND",
        status: "ONLINE",
      },
      live: {
        label: "// UPCOMING",
        title: "LIVE DATES",
        sub: "Where the sound takes me next.",
        tickets: "TICKETS",
        soldout: "SOLD OUT",
        tba: "// TO BE ANNOUNCED",
        tbaBody: "New dates are being locked in. Sign up below or follow the channels to be the first to know when the next ones drop.",
        tbaCta: "GET ON THE LIST",
        shows: [],
      },
      music: {
        label: "// LATEST",
        title: "MUSIC JUKEBOX",
        sub: "Recent releases, mixes and selections.",
        player: "FEATURED MIX",
        releases: "RELEASED TRACKS",
        sessions: "SESSIONS",
        listen: "LISTEN",
        tracklist: [
          { n: "001", title: "Codename 47", label: "Self-released", year: "2026", kind: "Single", url: "https://soundcloud.com/pipe-778963801/codename-47" },
          { n: "002", title: "Soultaker", label: "Self-released", year: "2026", kind: "Single", url: "https://soundcloud.com/pipe-778963801/soultaker" },
          { n: "003", title: "Mass Effect", label: "Self-released", year: "2026", kind: "Single", url: "https://soundcloud.com/pipe-778963801/masseffect" },
          { n: "004", title: "Serket", label: "Self-released", year: "2026", kind: "Single", url: "https://soundcloud.com/pipe-778963801/serket" },
          { n: "005", title: "Exodus", label: "Self-released", year: "2026", kind: "Single", url: "https://soundcloud.com/pipe-778963801/exodus" },
        ],
        sessionlist: [
          { n: "001", title: "Gravity Shift", label: "P1P3", year: "2026", kind: "Session", desc: "Melodic underground — no boundaries, pure flow", url: "https://soundcloud.com/pipe-778963801/gravityshift" },
          { n: "002", title: "Pharallel Lines",   label: "P1P3", year: "2026", kind: "Session", desc: "Full-throttle techno — built for the peak hour", url: "https://soundcloud.com/pipe-778963801/pharallellines" },
          { n: "003", title: "Groove Frecuency", label: "P1P3", year: "2026", kind: "Session", desc: "Raw rhythm, hardened groove — dance floor pressure", url: "https://soundcloud.com/pipe-778963801/groovefrecuency" },
        ],
      },
      about: {
        label: "// PROFILE",
        title: "ABOUT",
        bio1: "P1P3 is a DJ specialised in high-energy experiences within underground electronic music. His sound moves between Peak Time Techno (137–140 BPM), powerful Melodic Progressive (130–132 BPM) and Hard Drive / Hardgroove inspired by the energy of the contemporary European scene (140–142 BPM).",
        bio2: "His sets are defined by dynamic mixing, precise transitions and a progressive tension build that keeps the dancefloor in constant motion. Influenced by both modern techno and the rhythmic force of 2000s sounds, he develops sessions where energy and groove are the protagonists.",
        bio3: "P1P3 submitted a contest entry to HÖR Berlin — one of the most recognised international platforms for emerging and established artists in the global electronic scene. Through this exposure, a significant part of his digital audience comes from Germany, which concentrates a major share of his SoundCloud plays.",
        statement1: "Electronic music has been for me a constant process of learning and exploration. Each stage has led me to discover new ways of connecting with music — from my first mixes to the current search for my own sound within techno, melodic progressive and hard drive.",
        statement2: "Beyond genres, I am interested in understanding how technology and creativity can work together to create more immersive experiences. That is why I continue exploring new approaches to mixing, production and performance, including hybrid setups that combine hardware and software to expand the possibilities in the booth.",
        statement3: "I believe that an artist's evolution is not only about perfecting technique, but about staying curious. Listening, experimenting, making mistakes and trying again are all part of the process that drives my growth. My goal is to keep developing my own musical identity while discovering new ways to transmit energy, emotion and movement through every performance.",
        influencesTitle: "Musical Influences",
        influencesIntro: "My sound draws inspiration from artists who have shaped different corners of contemporary electronic music, from melodic storytelling to peak-time energy and groove-driven techno.",
        influences: ["Joris Voorn", "Enrico Sangiuliano", "Adam Beyer", "Kevin de Vries", "Konstantin Sibold"],
        influencesOutro: "While these artists have inspired my development, my goal is to continuously evolve and build a distinctive identity through techno, melodic progressive and hybrid performance concepts.",
        stats: [
          { v: "08", k: "Years touring" },
          { v: "47", k: "Countries" },
          { v: "12", k: "Releases" },
        ],
        presskit: "DOWNLOAD PRESS KIT",
        dossierCta: "READ THE DOSSIER",
      },
      dossier: {
        label: "// DOSSIER — 001 / FILE",
        title: "DIVE IN 2 THE SOUND",
        intro: "P1P3 is a DJ focused on building immersive sonic experiences within Melodic Techno and Peak Time Underground. His style is built on layering — sustaining a continuous flow with clean transitions and a narrative that keeps evolving across every set.",
        blocks: [
          { tag: "STYLE", body: "Melodic Techno · Progressive House · Peak Time / Atmospheric" },
          { tag: "APPROACH", body: "Progressive energy build, layered depth, precise transitions and an atmosphere-first musical selection." },
          { tag: "CONCEPT", body: "“Dive into the sound” — an invitation into an immersive sonic experience." },
        ],
        channels: "// DIRECT CHANNELS",
        contact: [
          { k: "EMAIL", v: "pulgawyf@gmail.com", href: "mailto:pulgawyf@gmail.com" },
          { k: "WHATSAPP", v: "+57 314 561 7834", href: "https://wa.me/573145617834" },
          { k: "WEB", v: "www.p1pe3music.com", href: "https://www.p1pe3music.com" },
        ],
        footnote: "FILE · P1P3_PRESSKIT.PDF · REV 26",
        download: "DOWNLOAD PDF",
      },
      rider: {
        label: "// TECHNICAL",
        title: "RIDER",
        sub: "Technical requirements for all performances. Please confirm all items before booking is finalized.",
        audio: {
          tag: "AUDIO SETUP",
          items: [
            { main: "1× Allen & Heath Xone:96", note: "preferred mixer" },
            { main: "1× Pioneer DJM-V10", note: "acceptable alternative" },
            { main: "DJM-900NXS2", note: "acceptable alternative" },
            { main: "4-channel minimum", note: "" },
            { main: "Sufficient space for hybrid setup", note: "notebook + Xone K2 + Roland TR-8S — notify 48h in advance" },
          ],
        },
        hospitality: {
          tag: "HOSPITALITY",
          items: [
            { main: "Still + sparkling water at booth", note: "throughout set" },
            { main: "Access pass for +1 guest", note: "" },
          ],
        },
        notes: {
          tag: "IMPORTANT NOTES",
          items: [
            "Headphone output MUST work on mixer",
            "100% own selection — no requests",
          ],
        },
        contactLabel: "RIDER QUERIES",
        contactEmail: "booking@p1p3.club",
      },
      booking: {
        label: "// CONTACT",
        title: "BOOKING",
        sub: "For shows, residencies and label requests.",
        fields: {
          name: "Name",
          email: "Email",
          date: "Event date",
          city: "City",
          budget: "Budget range",
          message: "Tell me about the event",
          send: "SEND REQUEST",
          sent: "REQUEST SENT — I’LL BE IN TOUCH",
        },
        direct: "Or write directly",
        bookingEmail: "pulgawyf@gmail.com",
        pressEmail: "press@p1p3.club",
      },
      footer: {
        rights: "ALL RIGHTS RESERVED",
        built: "Sound first. Everything else after.",
      },
    },

    es: {
      nav: { music: "MÚSICA", about: "BIO", dossier: "EPK", rider: "RIDER", booking: "BOOKING", live: "LIVE" },
      hero: {
        tagline: "SUMÉRGETE EN EL SONIDO",
        cta: "ENTRA AL CLUB",
        epk: "VER EPK",
        scroll: "BAJA",
        caption: "DJ / PRODUCTOR — PEAK TIME / UNDERGROUND MELÓDICO",
        status: "EN LÍNEA",
      },
      live: {
        label: "// PRÓXIMOS",
        title: "FECHAS EN VIVO",
        sub: "Donde el sonido me lleva.",
        tickets: "ENTRADAS",
        soldout: "AGOTADO",
        tba: "// PRÓXIMAMENTE",
        tbaBody: "Estamos cerrando nuevas fechas. Apúntate abajo o sigue los canales para ser el primero en enterarte cuando se anuncien.",
        tbaCta: "ENTRAR EN LA LISTA",
        shows: [],
      },
      music: {
        label: "// ÚLTIMO",
        title: "MÚSICA",
        sub: "Lanzamientos, mixes y selecciones recientes.",
        player: "MIX DESTACADO",
        releases: "LANZAMIENTOS",
        sessions: "SESIONES",
        listen: "ESCUCHAR",
        tracklist: [
          { n: "001", title: "Codename 47", label: "Auto-editado", year: "2026", kind: "Single", url: "https://soundcloud.com/pipe-778963801/codename-47" },
          { n: "002", title: "Soultaker", label: "Auto-editado", year: "2026", kind: "Single", url: "https://soundcloud.com/pipe-778963801/soultaker" },
          { n: "003", title: "Mass Effect", label: "Auto-editado", year: "2026", kind: "Single", url: "https://soundcloud.com/pipe-778963801/masseffect" },
          { n: "004", title: "Serket", label: "Auto-editado", year: "2026", kind: "Single", url: "https://soundcloud.com/pipe-778963801/serket" },
          { n: "005", title: "Exodus", label: "Auto-editado", year: "2026", kind: "Single", url: "https://soundcloud.com/pipe-778963801/exodus" },
        ],
        sessionlist: [
          { n: "001", title: "Beyond the Grid", label: "P1P3", year: "2026", kind: "Sesión", desc: "Underground melódico — sin límites, flujo puro", url: "https://soundcloud.com/pipe-778963801/beyondthegrid" },
          { n: "002", title: "Pharallel Lines",   label: "P1P3", year: "2026", kind: "Sesión", desc: "Techno a fondo — construido para el momento cumbre", url: "https://soundcloud.com/pipe-778963801/pharallellines" },
          { n: "003", title: "Groove Frecuency", label: "P1P3", year: "2026", kind: "Sesión", desc: "Ritmo crudo, groove endurecido — presión en la pista", url: "https://soundcloud.com/pipe-778963801/groovefrecuency" },
        ],
      },
      about: {
        label: "// PERFIL",
        title: "SOBRE MÍ",
        bio1: "P1P3 es un DJ especializado en experiencias de alta energía dentro de la música electrónica underground. Su sonido se mueve entre el Peak Time Techno (137–140 BPM), el Melodic Progressive de carácter potente (130–132 BPM) y el Hard Drive/Hardgroove inspirado en la energía de la escena europea contemporánea (140–142 BPM).",
        bio2: "Sus sets se caracterizan por una mezcla dinámica, transiciones precisas y una construcción progresiva de tensión que mantiene la pista en constante movimiento. Influenciado tanto por el techno moderno como por la fuerza rítmica de los sonidos de los años 2000, desarrolla sesiones donde la energía y el groove son los protagonistas.",
        bio3: "P1P3 participó en un concurso de la plataforma internacional HÖR Berlin, una de las vitrinas más reconocidas para artistas emergentes y consolidados de la escena electrónica global. Gracias a esta exposición, gran parte de su audiencia digital proviene de Alemania, país que concentra una parte importante de sus reproducciones en SoundCloud.",
        statement1: "La música electrónica ha sido para mí un proceso constante de aprendizaje y exploración. Cada etapa me ha llevado a descubrir nuevas formas de conectar con la música, desde mis primeras mezclas hasta la búsqueda actual de un sonido propio dentro del techno, el melodic progressive y el hard drive.",
        statement2: "Más allá de los géneros, me interesa entender cómo la tecnología y la creatividad pueden trabajar juntas para crear experiencias más inmersivas. Por eso continúo explorando nuevos enfoques de mezcla, producción y performance, incluyendo configuraciones híbridas que combinan hardware y software para ampliar las posibilidades en cabina.",
        statement3: "Creo que la evolución de un artista no consiste únicamente en perfeccionar la técnica, sino en mantener la curiosidad. Escuchar, experimentar, equivocarse y volver a intentarlo son parte del proceso que impulsa mi crecimiento. Mi objetivo es seguir explorando la musica tanto sonidos propios como de otros artistas dejandome sorprender por esos sonidos unicos y extraños que puedes descubrir y utilizar para transmitir energía, emoción y movimiento a través de cada session.",
        influencesTitle: "Influencias Musicales",
        influencesIntro: "Mi sonido se nutre de artistas que han dado forma a distintas áreas de la música electrónica contemporánea, desde narrativas melódicas hasta energía de peak time y techno impulsado por el groove.",
        influences: ["Joris Voorn", "Enrico Sangiuliano", "Adam Beyer", "Kevin de Vries", "Konstantin Sibold"],
        influencesOutro: "Aunque estos artistas han inspirado mi desarrollo, mi objetivo es evolucionar continuamente y construir una identidad propia a través del techno, el melodic progressive y conceptos de performance híbrido.",
        stats: [
          { v: "08", k: "Años de gira" },
          { v: "47", k: "Países" },
          { v: "12", k: "Lanzamientos" },
        ],
        presskit: "DESCARGAR PRESS KIT",
        dossierCta: "LEER EL DOSSIER",
      },
      dossier: {
        label: "// DOSSIER — 001 / FILE",
        title: "DIVE IN 2 THE SOUND",
        intro: "P1P3 es un DJ enfocado en crear experiencias sonoras inmersivas dentro del Melodic Techno / Peak Time Underground. Su estilo se basa en la construcción de capas para mantener el flujo continuo, con transiciones limpias y una narrativa que evoluciona constantemente en cada set.",
        blocks: [
          { tag: "ESTILO", body: "Melodic Techno · Progressive House · Peak Time / Atmospheric" },
          { tag: "ENFOQUE", body: "Construcción progresiva de energía, uso de capas para generar profundidad, transiciones precisas y selección musical orientada a atmósferas." },
          { tag: "CONCEPTO", body: "“Dive into the sound” — una invitación a entrar en una experiencia sonora inmersiva." },
        ],
        channels: "// CANALES DIRECTOS",
        contact: [
          { k: "EMAIL", v: "pulgawyf@gmail.com", href: "mailto:pulgawyf@gmail.com" },
          { k: "WHATSAPP", v: "+57 314 561 7834", href: "https://wa.me/573145617834" },
          { k: "WEB", v: "www.p1pe3music.com", href: "https://www.p1pe3music.com" },
        ],
        footnote: "ARCHIVO · P1P3_PRESSKIT.PDF · REV 26",
        download: "DESCARGAR PDF",
      },
      rider: {
        label: "// TÉCNICO",
        title: "RIDER",
        sub: "Requerimientos técnicos para todas las actuaciones. Por favor confirmar antes de cerrar el booking.",
        audio: {
          tag: "AUDIO",
          items: [
            { main: "1× Allen & Heath Xone:96", note: "mezclador preferido" },
            { main: "1× Pioneer DJM-V10", note: "alternativa aceptable" },
            { main: "DJM-900NXS2", note: "alternativa aceptable" },
            { main: "Mínimo 4 canales", note: "" },
            { main: "Espacio suficiente para setup híbrido", note: "notebook + Xone K2 + Roland TR-8S — notificar 48h antes" },
          ],
        },
        hospitality: {
          tag: "HOSPITALITY",
          items: [
            { main: "Agua (con y sin gas) en cabina durante el set", note: "" },
            { main: "Pase de acceso para +1 invitado", note: "" },
          ],
        },
        notes: {
          tag: "NOTAS IMPORTANTES",
          items: [
            "La salida de auriculares DEBE funcionar en el mixer",
            "100% selección propia — sin peticiones",
          ],
        },
        contactLabel: "CONSULTAS RIDER",
        contactEmail: "booking@p1p3.club",
      },
      booking: {
        label: "// CONTACTO",
        title: "BOOKING",
        sub: "Para shows, residencias y propuestas de sello.",
        fields: {
          name: "Nombre",
          email: "Correo",
          date: "Fecha del evento",
          city: "Ciudad",
          budget: "Rango de presupuesto",
          message: "Cuéntame del evento",
          send: "ENVIAR PETICIÓN",
          sent: "PETICIÓN ENVIADA — TE CONTESTO PRONTO",
        },
        direct: "O escribe directamente",
        bookingEmail: "pulgawyf@gmail.com",
        pressEmail: "press@p1p3.club",
      },
      footer: {
        rights: "TODOS LOS DERECHOS RESERVADOS",
        built: "El sonido primero. Lo demás después.",
      },
    },
  };
})();
